import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Navbar from "../components/Navbar";
import Results from '../components/Results'
import requests from '../requests';



const inter = Inter({ subsets: ['latin'] })

export default function Home({result}) {
  
  return (
    <>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>
      {/* Navbar */}
      <Navbar/>
      {/* Results */}
      <Results result={result}/>
    </>
  )
}


export async function getServerSideProps(context){
  const genre = context.query.genre
  const resp = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  const request = await resp.json()

  return   {
    props : {
      result : request["results"]
    }
  }
}
